#this should extend the django-wam environment
name: wam-app-openfred
dependencies:
- python=3.6
- pip:
  - django-geojson
  - django-leaflet
  - geojson
  - SQLAHelper
- conda-forge: 
  - configobj
  - geoalchemy2
  - shapely
  - sqlalchemy
  - yaml

